import type { ElementType } from "react";
import type { BoothSystem } from "@/components/workspace/BoothCanvas";

// ── Types ──────────────────────────────────────────────────────────
// Pure data-model for the PM booth workspace, split out of PMWorkspace.tsx so
// the component file carries behaviour, not static catalog data and shapes.
export type FasciaOption = 'classic' | 'full' | 'custom';
export type LightingPreset = 'neutral' | 'exhibition' | 'accent' | 'spotlight' | 'ambient';
export type DoorPosition = 'left' | 'center' | 'right';
export type DoorSide = 'front' | 'back' | 'left' | 'right';
export type DoorSwing = 'left-in' | 'right-in' | 'left-out' | 'right-out';
export type RoomWallFinish = 'white' | 'frosted' | 'glass' | 'dark';
export type RoomGraphicFit = 'cover' | 'contain' | 'stretch';
export type RoomTemplateKey = 'storage' | 'meeting' | 'utility';

export const ROOM_SIDE_OPTIONS: { value: DoorSide; label: string }[] = [
  {value:'front',label:'Front wall'},
  {value:'back',label:'Back wall'},
  {value:'left',label:'Left wall'},
  {value:'right',label:'Right wall'},
];

export interface BoothState { width:number; depth:number; height:number; system:BoothSystem; companyName:string; openFront:boolean; openBack:boolean; openLeft:boolean; openRight:boolean; fasciaEnabled:boolean; fasciaOption:FasciaOption; }
export interface WorkspacePlacedItem { id:string; catalogId:string; name:string; sku:string; qty:number; w:number; d:number; h:number; color:string; weight:number; x:number; z:number; rotation:number; rotationX?:number; rotationY?:number; rotationZ?:number; locked?:boolean; kind:'furniture'|'light'|'structure'|'fascia'|'asset'; shape?:CatItem['shape']; modelUrl?:string; source?:string; }
export interface WorkspaceRoom { id:string; name:string; width:number; depth:number; height:number; x:number; z:number; hasDoor:boolean; hasCeiling:boolean; doorSide:DoorSide; doorWidth:number; doorPosition:DoorPosition; doorSwing:DoorSwing; doorOpen:boolean; wallFinish:RoomWallFinish; floorColor:string; locked:boolean; designImageUrl?:string; designImageName?:string; designOpacity?:number; designWall:DoorSide; designFit:RoomGraphicFit; }
export interface PanelOverride { color?:string; brandText?:string; brandColor?:string; brandScale?:number; designImageUrl?:string; designImageName?:string; designOpacity?:number; }
export interface Note { id:string; text:string; color:string; createdAt:string; }
export interface Snapshot { id:string; name:string; data:WSData; createdAt:string; }
export interface WSData { booth:BoothState; themeIdx:number; wallFinishIdx:number; frameFinishIdx:number; fasciaFinishIdx:number; carpetIdx:number; lightingPreset:LightingPreset; placedItems:WorkspacePlacedItem[]; rooms:WorkspaceRoom[]; notes:Note[]; panelOverrides:Record<string,PanelOverride>; frontSupportPositions:number[]; suppressedDefaultPositions:number[]; }
export type SaveStatus = 'idle' | 'dirty' | 'saving' | 'saved' | 'error';
export type FeedbackFilter = 'open' | 'all' | 'resolved';

// ── Catalog ────────────────────────────────────────────────────────
export interface CatItem { id:string; name:string; sku:string; dim:string; inStand:number; icon:ElementType; family?:string; price?:number; stock?:number; lowStockAt?:number; shape?:'round_table'|'rect_table'|'counter'|'shelf'|'wall_shelf'|'cabinet'|'cube'|'chair'|'bar_stool'|'light'|'rail_light'|'box'; modelUrl?:string; previewUrl?:string; furnitureCategory?:FurnitureCategory; }
export type FurnitureCategory = 'all' | 'chairs' | 'stools' | 'seating' | 'tables' | 'counters' | 'displays' | 'storage' | 'shelves' | 'appliances' | 'lighting' | 'decor' | 'parts';

export const ENS_FURNITURE_ITEMS: Omit<CatItem,'icon'>[] = [
  {id:'ens-103', name:'AHSAP YUVARLAK MASA - WOODEN ROUND TABLE', sku:'103', dim:'0.70 x 0.70 x 0.78', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'round_table', modelUrl:'/ens-workspace-assets/ens-furniture/103-wooden-round-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/103-wooden-round-table.png'},
  {id:'ens-105', name:'AHSAP KARE MASA - WOODEN SQUARE TABLE', sku:'105', dim:'0.71 x 0.71 x 0.77', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rect_table', modelUrl:'/ens-workspace-assets/ens-furniture/105-wooden-square-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/105-wooden-square-table.png'},
  {id:'ens-110', name:'CAM MASA - GLASS TABLE', sku:'110', dim:'0.80 x 0.80 x 0.76', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'round_table', modelUrl:'/ens-workspace-assets/ens-furniture/110-glass-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/110-glass-table.png'},
  {id:'ens-111', name:'DIKDORTGEN MASA - RECTANGLE TABLE', sku:'111', dim:'1.11 x 0.81 x 0.77', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rect_table', modelUrl:'/ens-workspace-assets/ens-furniture/111-rectangle-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/111-rectangle-table.png'},
  {id:'ens-112', name:'LAKE SEHPA - LACQUER COFFEE TABLE', sku:'112', dim:'0.96 x 0.56 x 0.41', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rect_table', modelUrl:'/ens-workspace-assets/ens-furniture/112-lacquer-coffee-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/112-lacquer-coffee-table.png'},
  {id:'ens-211', name:'TOPLANTI MASASI - MEETING TABLE', sku:'211', dim:'1.41 x 0.71 x 0.77', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rect_table', modelUrl:'/ens-workspace-assets/ens-furniture/211-meeting-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/211-meeting-table.png'},
  {id:'ens-212', name:'MASA - TABLE', sku:'212', dim:'1.41 x 0.81 x 0.77', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rect_table', modelUrl:'/ens-workspace-assets/ens-furniture/212-table.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/212-table.png'},
  {id:'ens-312s', name:'TEK KISILIK KOLTUK SIYAH - ARMCHAIR BLACK', sku:'312-S', dim:'0.78 x 0.84 x 0.90', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'chair', modelUrl:'/ens-workspace-assets/ens-furniture/armchair-312s.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/armchair-312s.png'},
  {id:'ens-255b', name:'DERI BAR SANDALYESI - LEATHER BAR CHAIR', sku:'255-B', dim:'0.41 x 0.43 x 1.32', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'bar_stool', modelUrl:'/ens-workspace-assets/ens-furniture/bar-chair-255b.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/bar-chair-255b.png'},
  {id:'ens-255s', name:'AVEA DERI BAR TABURESI SIYAH - BLACK LEATHER BAR STOOL', sku:'255-S', dim:'0.41 x 0.43 x 0.79', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'bar_stool', modelUrl:'/ens-workspace-assets/ens-furniture/bar-stool-255s.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/bar-stool-255s.png'},
  {id:'ens-413', name:'BROSURLUK - BROCHURE RACK', sku:'413', dim:'0.31 x 0.26 x 0.77', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'shelf', modelUrl:'/ens-workspace-assets/ens-furniture/brochure-rack-413.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/brochure-rack-413.png'},
  {id:'ens-213', name:'DEPO DOLABI - STORAGE CABINET', sku:'213', dim:'1.04 x 0.44 x 1.95', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/cabinet-213.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/cabinet-213.png'},
  {id:'ens-216', name:'KILITLI DOLAP - LOCKABLE CABINET', sku:'216', dim:'1.07 x 0.46 x 0.82', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/cabinet-216.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/cabinet-216.png'},
  {id:'ens-461', name:'ALCAK DOLAP - LOW CABINET', sku:'461', dim:'0.48 x 1.00 x 1.00', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/cabinet-461.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/cabinet-461.png'},
  {id:'ens-149', name:'PLASTIK HARE SANDALYE - PLASTIC CHAIR', sku:'149', dim:'0.50 x 0.45 x 0.88', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'chair', modelUrl:'/ens-workspace-assets/ens-furniture/chair-149.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/chair-149.png'},
  {id:'ens-250b', name:'AHSAP SANDALYE BEYAZ - WHITE WOOD CHAIR', sku:'250-B', dim:'0.44 x 0.44 x 0.81', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'chair', modelUrl:'/ens-workspace-assets/ens-furniture/chair-250b.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/chair-250b.png'},
  {id:'ens-309', name:'DERI SANDALYE - LEATHER CHAIR', sku:'309', dim:'0.50 x 0.50 x 0.81', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'chair', modelUrl:'/ens-workspace-assets/ens-furniture/chair-309.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/chair-309.png'},
  {id:'ens-315', name:'VESTIYER - CLOTHES RACK', sku:'315', dim:'0.37 x 0.37 x 1.62', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/clothes-rack-315.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/clothes-rack-315.png'},
  {id:'ens-208', name:'BANKO - COUNTER', sku:'208', dim:'1.04 x 0.59 x 0.97', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'counter', modelUrl:'/ens-workspace-assets/ens-furniture/counter-208.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/counter-208.png'},
  {id:'ens-209', name:'GENIS BANKO - WIDE COUNTER', sku:'209', dim:'1.04 x 0.59 x 0.97', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'counter', modelUrl:'/ens-workspace-assets/ens-furniture/counter-209.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/counter-209.png'},
  {id:'ens-215', name:'KOSE BANKO - CORNER COUNTER', sku:'215', dim:'1.06 x 0.44 x 0.98', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'counter', modelUrl:'/ens-workspace-assets/ens-furniture/counter-215.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/counter-215.png'},
  {id:'ens-458', name:'ISIKLI BANKO - LIGHTED COUNTER', sku:'458', dim:'0.54 x 1.04 x 1.06', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'counter', modelUrl:'/ens-workspace-assets/ens-furniture/counter-458.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/counter-458.png'},
  {id:'ens-508', name:'YUVARLAK BANKO - ROUND COUNTER', sku:'508', dim:'1.24 x 0.64 x 0.97', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'counter', modelUrl:'/ens-workspace-assets/ens-furniture/counter-508.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/counter-508.png'},
  {id:'ens-217', name:'TESHIR KUPU - DISPLAY CUBE', sku:'217', dim:'0.50 x 0.50 x 0.50', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cube', modelUrl:'/ens-workspace-assets/ens-furniture/display-cube-217.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/display-cube-217.png'},
  {id:'ens-218', name:'BUYUK TESHIR KUPU - LARGE DISPLAY CUBE', sku:'218', dim:'0.75 x 0.75 x 0.75', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cube', modelUrl:'/ens-workspace-assets/ens-furniture/display-cube-218.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/display-cube-218.png'},
  {id:'ens-512', name:'DAGITIM PANOSU - DISTRIBUTION PANEL', sku:'512', dim:'0.48 x 0.20 x 0.26', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/distribution-panel-512.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/distribution-panel-512.png'},
  {id:'ens-231', name:'AHSAP KAPI - WOODEN DOOR', sku:'231', dim:'0.83 x 0.07 x 2.08', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/door-231.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/door-231.png'},
  {id:'ens-422', name:'MESRUBAT DOLABI - DRINK REFRIGERATOR', sku:'422', dim:'0.55 x 0.61 x 1.70', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/drink-fridge-422.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/drink-fridge-422.png'},
  {id:'ens-417', name:'100 W 3 RENKLI LAMBA - 100 W 3-COLORED LAMP', sku:'417', dim:'0.30 x 0.16 x 0.28', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rail_light', modelUrl:'/ens-workspace-assets/ens-furniture/exhibition-spotlight-417.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/exhibition-spotlight-417.png'},
  {id:'ens-ext422', name:'UZATMA KABLOSU - EXTENSION CORD', sku:'EXT-422', dim:'0.52 x 0.27 x 0.05', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/extension-cord-422.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/extension-cord-422.png'},
  {id:'ens-418', name:'100 W GRI PROJEKTOR - 100 W SPOTLIGHT LAMP', sku:'418', dim:'0.26 x 0.15 x 0.21', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rail_light', modelUrl:'/ens-workspace-assets/ens-furniture/floodlight-418.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/floodlight-418.png'},
  {id:'ens-419', name:'100 W LED KOLLU PROJEKTOR - 100 W SPOTLIGHT LAMP', sku:'419', dim:'0.22 x 0.22 x 1.49', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'rail_light', modelUrl:'/ens-workspace-assets/ens-furniture/floor-spotlight-419.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/floor-spotlight-419.png'},
  {id:'ens-431', name:'AHSAP CICEKLIK - WOOD FLORAL', sku:'431', dim:'0.90 x 0.20 x 0.87', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/floral-stand-431.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/floral-stand-431.png'},
  {id:'ens-411', name:'BUZDOLABI - REFRIGERATOR', sku:'411', dim:'0.56 x 0.58 x 0.83', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/fridge-411.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/fridge-411.png'},
  {id:'ens-447', name:'BUYUK BUZDOLABI - LARGE REFRIGERATOR', sku:'447', dim:'0.56 x 0.62 x 1.80', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/fridge-447.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/fridge-447.png'},
  {id:'ens-402', name:'DIZUSTU BILGISAYAR - LAPTOP', sku:'402', dim:'0.33 x 0.27 x 0.23', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/laptop-402.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/laptop-402.png'},
  {id:'ens-326s', name:'OFIS SANDALYESI - OFFICE CHAIR', sku:'326-S', dim:'0.53 x 0.55 x 1.12', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'chair', modelUrl:'/ens-workspace-assets/ens-furniture/office-chair-326s.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/office-chair-326s.png'},
  {id:'ens-221', name:'PANEL - PANEL', sku:'221', dim:'0.85 x 0.17 x 2.14', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/panel-221.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/panel-221.png'},
  {id:'ens-321', name:'BITKI - PLANT', sku:'321', dim:'0.49 x 0.68 x 1.62', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/plant-321.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/plant-321.png'},
  {id:'ens-224', name:'RAF - SHELF', sku:'224', dim:'1.03 x 0.33 x 0.10', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'shelf', modelUrl:'/ens-workspace-assets/ens-furniture/shelf-224.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/shelf-224.png'},
  {id:'ens-201', name:'ALCAK VITRIN - LOW SHOWCASE', sku:'201', dim:'1.02 x 0.54 x 0.94', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/showcase-201.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/showcase-201.png'},
  {id:'ens-205', name:'DAR VITRIN - NARROW SHOWCASE', sku:'205', dim:'0.51 x 0.40 x 1.99', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/showcase-205.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/showcase-205.png'},
  {id:'ens-206', name:'YUKSEK VITRIN - TALL SHOWCASE', sku:'206', dim:'1.02 x 0.54 x 1.99', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/showcase-206.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/showcase-206.png'},
  {id:'ens-406', name:'ISIKLI VITRIN - LIGHTED SHOWCASE', sku:'406', dim:'0.95 x 0.48 x 0.84', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/showcase-406.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/showcase-406.png'},
  {id:'ens-440', name:'EVYE DOLAPLI - SINK CABINET', sku:'440', dim:'0.52 x 0.47 x 0.87', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'cabinet', modelUrl:'/ens-workspace-assets/ens-furniture/sink-cabinet-440.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/sink-cabinet-440.png'},
  {id:'ens-313s', name:'CIFT KISILIK KOLTUK SIYAH - DOUBLE SOFA BLACK', sku:'313-S', dim:'1.39 x 0.84 x 0.90', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/sofa-313s.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/sofa-313s.png'},
  {id:'ens-401', name:'TV - TV', sku:'401', dim:'1.23 x 0.30 x 1.40', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/tv-401.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/tv-401.png'},
  {id:'ens-318', name:'COP KOVASI - WASTE BIN', sku:'318', dim:'0.29 x 0.29 x 0.26', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/waste-bin-318.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/waste-bin-318.png'},
  {id:'ens-412', name:'SEBIL - WATER FOUNTAIN', sku:'412', dim:'0.31 x 0.32 x 1.47', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'box', modelUrl:'/ens-workspace-assets/ens-furniture/water-fountain-412.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/water-fountain-412.png'},
  {id:'ens-513', name:'TEL BAR SANDALYESI - WIRE BLACK BAR CHAIR', sku:'513', dim:'0.40 x 0.39 x 1.42', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'bar_stool', modelUrl:'/ens-workspace-assets/ens-furniture/wire-bar-chair-513.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/wire-bar-chair-513.png'},
  {id:'ens-307', name:'Z BAR TABURESI - Z BAR STOOL', sku:'307', dim:'0.34 x 0.32 x 0.71', inStand:0, family:'ENS Furniture', price:0, stock:99, shape:'bar_stool', modelUrl:'/ens-workspace-assets/ens-furniture/z-bar-stool-307.glb', previewUrl:'/ens-workspace-assets/ens-furniture/previews/z-bar-stool-307.png'},
  // 316-K has no model in ENSFurnitures; kept from the previous set.
  {id:'sedef-316-k', name:'DERI PUF KIRMIZI - LEATHER POUFFE RED', sku:'316-K', dim:'0.45 x 0.45 x 0.45', inStand:0, family:'Sedef Refined Furniture', price:0, stock:99, shape:'cube', modelUrl:'/ens-workspace-assets/sedef_remaining_furniture_refined_v2/glb_models/316-K%20DERI%20PUF%20KIRMIZI%20-%20LEATHER%20POUFFE%20RED.glb'},
];

/** Kept as an alias so existing imports and saved workspaces keep resolving. */
export const SEDEF_FURNITURE_ITEMS = ENS_FURNITURE_ITEMS;
