"""workspace parity tables

Revision ID: 4d65ce80a2e9
Revises: e4288b112f80
Create Date: 2026-03-27 19:37:48.029536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d65ce80a2e9'
down_revision = 'e4288b112f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_assets_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_assets_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('workspace_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('scene_data', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_versions_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_versions_workspace_id'))

    op.drop_table('workspace_versions')
    with op.batch_alter_table('workspace_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_assets_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_assets_kind'))

    op.drop_table('workspace_assets')
    # ### end Alembic commands ###
