/**
 * add-auth.cjs
 * Adds auth.login.*, auth.signup.*, auth.forgotPassword.*, auth.resetPassword.*
 * keys to all 11 locale files.
 */
const fs = require("fs");
const path = require("path");

const LOCALES_DIR = path.join(__dirname, "../src/i18n/locales");

const TRANSLATIONS = {
  en: {
    login: {
      pageTitle: "Sign In | ENS",
      title: "Welcome back",
      description: "Sign in to access your workspace",
      emailLabel: "Email",
      emailPlaceholder: "name@company.com",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      forgotPassword: "Forgot password?",
      rememberMe: "Keep me signed in for 30 days",
      submit: "Sign In",
      submitting: "Signing in...",
      lockedBtn: "Locked",
      lockMessage: "Account temporarily locked. Try again in {{time}}.",
      signInError: "Could not sign in.",
      attemptsRemaining_one: "{{count}} sign-in attempt remaining before temporary lockout",
      attemptsRemaining_other: "{{count}} sign-in attempts remaining before temporary lockout",
      noAccount: "Don't have an account?",
      signUpFree: "Sign up free",
      devSection: "Local Test Accounts",
      showPassword: "Show password",
      hidePassword: "Hide password",
      validation: {
        email: "Invalid email address",
        passwordMin: "Password must be at least 8 characters",
      },
    },
    signup: {
      pageTitle: "Create Account | ENS",
      title: "Create client account",
      description: "Client signup creates a review account pending agency approval",
      fullNameLabel: "Full Name",
      fullNamePlaceholder: "John Doe",
      companyLabel: "Company",
      companyPlaceholder: "Acme Exhibits",
      workEmailLabel: "Work Email",
      passwordLabel: "Password",
      passwordPlaceholder: "Create a password",
      confirmPasswordLabel: "Confirm Password",
      confirmPasswordPlaceholder: "Confirm your password",
      termsLabel: "I agree to the",
      termsOfService: "Terms of Service",
      and: "and",
      privacyPolicy: "Privacy Policy",
      submit: "Create Client Account",
      submitting: "Creating account...",
      createError: "Could not create account.",
      haveAccount: "Already have an account?",
      signIn: "Sign in",
      clientOnlyNote: "Public signup is limited to clients. Project managers and chiefs must be invited by an organization owner.",
      showPassword: "Show password",
      hidePassword: "Hide password",
      showConfirmPassword: "Show confirmation password",
      hideConfirmPassword: "Hide confirmation password",
      strength: {
        weak: "Weak",
        fair: "Fair",
        good: "Good",
        strong: "Strong",
        suffix: "password",
      },
      validation: {
        nameMin: "Name must be at least 2 characters",
        companyMin: "Company must be at least 2 characters",
        email: "Invalid email address",
        passwordMin: "Password must be at least 8 characters",
        passwordUpper: "Must contain an uppercase letter",
        passwordNumber: "Must contain a number",
        confirmRequired: "Please confirm your password",
        termsRequired: "You must accept the terms",
        passwordsMismatch: "Passwords don't match",
      },
    },
    forgotPassword: {
      pageTitle: "Reset Password | ENS",
      title: "Reset password",
      description: "Enter your email and we'll send you a reset link",
      emailLabel: "Email address",
      submit: "Send Reset Link",
      submitting: "Sending link...",
      sentTitle: "Check your inbox",
      sentTo: "We sent a password reset link to",
      checkSpam: "Check your spam folder if you don't see it within a few minutes.",
      resending: "Sending...",
      resendIn: "Resend in {{seconds}}s",
      resendEmail: "Resend email",
      differentEmail: "Use a different email",
      backToLogin: "Back to login",
      validation: {
        email: "Please enter a valid email address",
      },
    },
    resetPassword: {
      pageTitle: "Set New Password | ENS",
      title: "Set new password",
      description: "Choose a strong password for your account",
      newPasswordLabel: "New Password",
      confirmPasswordLabel: "Confirm Password",
      passwordPlaceholder: "••••••••",
      submit: "Update Password",
      submitting: "Updating password...",
      successTitle: "Password updated",
      successMessage: "Your password has been updated successfully. You can now sign in with your new credentials.",
      continueToSignIn: "Continue to Sign In",
      backToLogin: "Back to login",
      showPassword: "Show password",
      hidePassword: "Hide password",
      showConfirmPassword: "Show confirmation password",
      hideConfirmPassword: "Hide confirmation password",
      requirements: {
        length: "At least 8 characters",
        uppercase: "One uppercase letter",
        number: "One number",
      },
      strength: {
        weak: "Weak",
        fair: "Fair",
        good: "Good",
        strong: "Strong",
        suffix: "password",
      },
      validation: {
        passwordMin: "Password must be at least 8 characters",
        passwordUpper: "Must contain at least one uppercase letter",
        passwordNumber: "Must contain at least one number",
        confirmRequired: "Please confirm your password",
        passwordsMismatch: "Passwords don't match",
      },
    },
  },
  de: {
    login: {
      pageTitle: "Anmelden | ENS",
      title: "Willkommen zurück",
      description: "Melden Sie sich an, um auf Ihren Arbeitsbereich zuzugreifen",
      emailLabel: "E-Mail",
      emailPlaceholder: "name@unternehmen.com",
      passwordLabel: "Passwort",
      passwordPlaceholder: "Passwort eingeben",
      forgotPassword: "Passwort vergessen?",
      rememberMe: "30 Tage angemeldet bleiben",
      submit: "Anmelden",
      submitting: "Wird angemeldet...",
      lockedBtn: "Gesperrt",
      lockMessage: "Konto vorübergehend gesperrt. Versuchen Sie es in {{time}} erneut.",
      signInError: "Anmeldung fehlgeschlagen.",
      attemptsRemaining_one: "Noch {{count}} Anmeldeversuch vor temporärer Sperrung",
      attemptsRemaining_other: "Noch {{count}} Anmeldeversuche vor temporärer Sperrung",
      noAccount: "Noch kein Konto?",
      signUpFree: "Kostenlos registrieren",
      devSection: "Lokale Testkonten",
      showPassword: "Passwort anzeigen",
      hidePassword: "Passwort ausblenden",
      validation: {
        email: "Ungültige E-Mail-Adresse",
        passwordMin: "Passwort muss mindestens 8 Zeichen lang sein",
      },
    },
    signup: {
      pageTitle: "Konto erstellen | ENS",
      title: "Kundenkonto erstellen",
      description: "Die öffentliche Registrierung erstellt ein Review-Konto, das von der Agentur genehmigt werden muss",
      fullNameLabel: "Vollständiger Name",
      fullNamePlaceholder: "Max Mustermann",
      companyLabel: "Unternehmen",
      companyPlaceholder: "Muster GmbH",
      workEmailLabel: "Geschäftliche E-Mail",
      passwordLabel: "Passwort",
      passwordPlaceholder: "Passwort erstellen",
      confirmPasswordLabel: "Passwort bestätigen",
      confirmPasswordPlaceholder: "Passwort bestätigen",
      termsLabel: "Ich stimme den",
      termsOfService: "Nutzungsbedingungen",
      and: "und der",
      privacyPolicy: "Datenschutzrichtlinie",
      submit: "Kundenkonto erstellen",
      submitting: "Konto wird erstellt...",
      createError: "Konto konnte nicht erstellt werden.",
      haveAccount: "Bereits ein Konto?",
      signIn: "Anmelden",
      clientOnlyNote: "Die öffentliche Registrierung ist auf Kunden beschränkt. Projektmanager und Chefs müssen von einem Organisationsinhaber eingeladen werden.",
      showPassword: "Passwort anzeigen",
      hidePassword: "Passwort ausblenden",
      showConfirmPassword: "Bestätigungspasswort anzeigen",
      hideConfirmPassword: "Bestätigungspasswort ausblenden",
      strength: {
        weak: "Schwach",
        fair: "Ausreichend",
        good: "Gut",
        strong: "Stark",
        suffix: "Passwort",
      },
      validation: {
        nameMin: "Name muss mindestens 2 Zeichen lang sein",
        companyMin: "Unternehmen muss mindestens 2 Zeichen lang sein",
        email: "Ungültige E-Mail-Adresse",
        passwordMin: "Passwort muss mindestens 8 Zeichen lang sein",
        passwordUpper: "Muss einen Großbuchstaben enthalten",
        passwordNumber: "Muss eine Zahl enthalten",
        confirmRequired: "Bitte Passwort bestätigen",
        termsRequired: "Sie müssen die Bedingungen akzeptieren",
        passwordsMismatch: "Passwörter stimmen nicht überein",
      },
    },
    forgotPassword: {
      pageTitle: "Passwort zurücksetzen | ENS",
      title: "Passwort zurücksetzen",
      description: "Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Link",
      emailLabel: "E-Mail-Adresse",
      submit: "Link senden",
      submitting: "Link wird gesendet...",
      sentTitle: "Posteingang prüfen",
      sentTo: "Wir haben einen Link zum Zurücksetzen des Passworts gesendet an",
      checkSpam: "Prüfen Sie Ihren Spam-Ordner, falls Sie die E-Mail nicht innerhalb weniger Minuten erhalten.",
      resending: "Wird gesendet...",
      resendIn: "Erneut senden in {{seconds}}s",
      resendEmail: "E-Mail erneut senden",
      differentEmail: "Andere E-Mail verwenden",
      backToLogin: "Zurück zur Anmeldung",
      validation: {
        email: "Bitte geben Sie eine gültige E-Mail-Adresse ein",
      },
    },
    resetPassword: {
      pageTitle: "Neues Passwort setzen | ENS",
      title: "Neues Passwort setzen",
      description: "Wählen Sie ein sicheres Passwort für Ihr Konto",
      newPasswordLabel: "Neues Passwort",
      confirmPasswordLabel: "Passwort bestätigen",
      passwordPlaceholder: "••••••••",
      submit: "Passwort aktualisieren",
      submitting: "Passwort wird aktualisiert...",
      successTitle: "Passwort aktualisiert",
      successMessage: "Ihr Passwort wurde erfolgreich aktualisiert. Sie können sich jetzt mit Ihren neuen Zugangsdaten anmelden.",
      continueToSignIn: "Weiter zur Anmeldung",
      backToLogin: "Zurück zur Anmeldung",
      showPassword: "Passwort anzeigen",
      hidePassword: "Passwort ausblenden",
      showConfirmPassword: "Bestätigungspasswort anzeigen",
      hideConfirmPassword: "Bestätigungspasswort ausblenden",
      requirements: {
        length: "Mindestens 8 Zeichen",
        uppercase: "Ein Großbuchstabe",
        number: "Eine Zahl",
      },
      strength: {
        weak: "Schwach",
        fair: "Ausreichend",
        good: "Gut",
        strong: "Stark",
        suffix: "Passwort",
      },
      validation: {
        passwordMin: "Passwort muss mindestens 8 Zeichen lang sein",
        passwordUpper: "Muss mindestens einen Großbuchstaben enthalten",
        passwordNumber: "Muss mindestens eine Zahl enthalten",
        confirmRequired: "Bitte Passwort bestätigen",
        passwordsMismatch: "Passwörter stimmen nicht überein",
      },
    },
  },
  fr: {
    login: {
      pageTitle: "Connexion | ENS",
      title: "Bon retour",
      description: "Connectez-vous pour accéder à votre espace de travail",
      emailLabel: "E-mail",
      emailPlaceholder: "nom@entreprise.com",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "Entrez votre mot de passe",
      forgotPassword: "Mot de passe oublié ?",
      rememberMe: "Rester connecté pendant 30 jours",
      submit: "Se connecter",
      submitting: "Connexion en cours...",
      lockedBtn: "Bloqué",
      lockMessage: "Compte temporairement bloqué. Réessayez dans {{time}}.",
      signInError: "Connexion impossible.",
      attemptsRemaining_one: "{{count}} tentative de connexion restante avant blocage temporaire",
      attemptsRemaining_other: "{{count}} tentatives de connexion restantes avant blocage temporaire",
      noAccount: "Pas encore de compte ?",
      signUpFree: "S'inscrire gratuitement",
      devSection: "Comptes de test locaux",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      validation: {
        email: "Adresse e-mail invalide",
        passwordMin: "Le mot de passe doit contenir au moins 8 caractères",
      },
    },
    signup: {
      pageTitle: "Créer un compte | ENS",
      title: "Créer un compte client",
      description: "L'inscription publique crée un compte de révision en attente d'approbation",
      fullNameLabel: "Nom complet",
      fullNamePlaceholder: "Jean Dupont",
      companyLabel: "Entreprise",
      companyPlaceholder: "Acme Expositions",
      workEmailLabel: "E-mail professionnel",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "Créer un mot de passe",
      confirmPasswordLabel: "Confirmer le mot de passe",
      confirmPasswordPlaceholder: "Confirmer votre mot de passe",
      termsLabel: "J'accepte les",
      termsOfService: "Conditions d'utilisation",
      and: "et la",
      privacyPolicy: "Politique de confidentialité",
      submit: "Créer le compte client",
      submitting: "Création du compte...",
      createError: "Impossible de créer le compte.",
      haveAccount: "Déjà un compte ?",
      signIn: "Se connecter",
      clientOnlyNote: "L'inscription publique est limitée aux clients. Les chefs de projet et responsables doivent être invités par un propriétaire d'organisation.",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      showConfirmPassword: "Afficher la confirmation du mot de passe",
      hideConfirmPassword: "Masquer la confirmation du mot de passe",
      strength: {
        weak: "Faible",
        fair: "Moyen",
        good: "Bon",
        strong: "Fort",
        suffix: "mot de passe",
      },
      validation: {
        nameMin: "Le nom doit contenir au moins 2 caractères",
        companyMin: "L'entreprise doit contenir au moins 2 caractères",
        email: "Adresse e-mail invalide",
        passwordMin: "Le mot de passe doit contenir au moins 8 caractères",
        passwordUpper: "Doit contenir une lettre majuscule",
        passwordNumber: "Doit contenir un chiffre",
        confirmRequired: "Veuillez confirmer votre mot de passe",
        termsRequired: "Vous devez accepter les conditions",
        passwordsMismatch: "Les mots de passe ne correspondent pas",
      },
    },
    forgotPassword: {
      pageTitle: "Réinitialiser le mot de passe | ENS",
      title: "Réinitialiser le mot de passe",
      description: "Entrez votre e-mail et nous vous enverrons un lien de réinitialisation",
      emailLabel: "Adresse e-mail",
      submit: "Envoyer le lien",
      submitting: "Envoi en cours...",
      sentTitle: "Vérifiez votre boîte mail",
      sentTo: "Nous avons envoyé un lien de réinitialisation à",
      checkSpam: "Vérifiez vos spams si vous ne le voyez pas dans quelques minutes.",
      resending: "Envoi en cours...",
      resendIn: "Renvoyer dans {{seconds}}s",
      resendEmail: "Renvoyer l'e-mail",
      differentEmail: "Utiliser une autre adresse e-mail",
      backToLogin: "Retour à la connexion",
      validation: {
        email: "Veuillez saisir une adresse e-mail valide",
      },
    },
    resetPassword: {
      pageTitle: "Nouveau mot de passe | ENS",
      title: "Définir un nouveau mot de passe",
      description: "Choisissez un mot de passe fort pour votre compte",
      newPasswordLabel: "Nouveau mot de passe",
      confirmPasswordLabel: "Confirmer le mot de passe",
      passwordPlaceholder: "••••••••",
      submit: "Mettre à jour le mot de passe",
      submitting: "Mise à jour en cours...",
      successTitle: "Mot de passe mis à jour",
      successMessage: "Votre mot de passe a été mis à jour avec succès. Vous pouvez maintenant vous connecter avec vos nouveaux identifiants.",
      continueToSignIn: "Continuer vers la connexion",
      backToLogin: "Retour à la connexion",
      showPassword: "Afficher le mot de passe",
      hidePassword: "Masquer le mot de passe",
      showConfirmPassword: "Afficher la confirmation",
      hideConfirmPassword: "Masquer la confirmation",
      requirements: {
        length: "Au moins 8 caractères",
        uppercase: "Une lettre majuscule",
        number: "Un chiffre",
      },
      strength: {
        weak: "Faible",
        fair: "Moyen",
        good: "Bon",
        strong: "Fort",
        suffix: "mot de passe",
      },
      validation: {
        passwordMin: "Le mot de passe doit contenir au moins 8 caractères",
        passwordUpper: "Doit contenir au moins une lettre majuscule",
        passwordNumber: "Doit contenir au moins un chiffre",
        confirmRequired: "Veuillez confirmer votre mot de passe",
        passwordsMismatch: "Les mots de passe ne correspondent pas",
      },
    },
  },
  es: {
    login: {
      pageTitle: "Iniciar sesión | ENS",
      title: "Bienvenido de nuevo",
      description: "Inicia sesión para acceder a tu espacio de trabajo",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "nombre@empresa.com",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "Introduce tu contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      rememberMe: "Mantenerme conectado 30 días",
      submit: "Iniciar sesión",
      submitting: "Iniciando sesión...",
      lockedBtn: "Bloqueado",
      lockMessage: "Cuenta bloqueada temporalmente. Vuelve a intentarlo en {{time}}.",
      signInError: "No se pudo iniciar sesión.",
      attemptsRemaining_one: "{{count}} intento de inicio de sesión restante antes del bloqueo temporal",
      attemptsRemaining_other: "{{count}} intentos de inicio de sesión restantes antes del bloqueo temporal",
      noAccount: "¿No tienes cuenta?",
      signUpFree: "Regístrate gratis",
      devSection: "Cuentas de prueba locales",
      showPassword: "Mostrar contraseña",
      hidePassword: "Ocultar contraseña",
      validation: {
        email: "Dirección de correo electrónico inválida",
        passwordMin: "La contraseña debe tener al menos 8 caracteres",
      },
    },
    signup: {
      pageTitle: "Crear cuenta | ENS",
      title: "Crear cuenta de cliente",
      description: "El registro público crea una cuenta de revisión pendiente de aprobación",
      fullNameLabel: "Nombre completo",
      fullNamePlaceholder: "Juan García",
      companyLabel: "Empresa",
      companyPlaceholder: "Acme Exposiciones",
      workEmailLabel: "Correo profesional",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "Crear una contraseña",
      confirmPasswordLabel: "Confirmar contraseña",
      confirmPasswordPlaceholder: "Confirmar tu contraseña",
      termsLabel: "Acepto los",
      termsOfService: "Términos de servicio",
      and: "y la",
      privacyPolicy: "Política de privacidad",
      submit: "Crear cuenta de cliente",
      submitting: "Creando cuenta...",
      createError: "No se pudo crear la cuenta.",
      haveAccount: "¿Ya tienes cuenta?",
      signIn: "Iniciar sesión",
      clientOnlyNote: "El registro público está limitado a clientes. Los directores de proyecto y responsables deben ser invitados por un propietario de organización.",
      showPassword: "Mostrar contraseña",
      hidePassword: "Ocultar contraseña",
      showConfirmPassword: "Mostrar confirmación de contraseña",
      hideConfirmPassword: "Ocultar confirmación de contraseña",
      strength: {
        weak: "Débil",
        fair: "Regular",
        good: "Buena",
        strong: "Fuerte",
        suffix: "contraseña",
      },
      validation: {
        nameMin: "El nombre debe tener al menos 2 caracteres",
        companyMin: "La empresa debe tener al menos 2 caracteres",
        email: "Dirección de correo electrónico inválida",
        passwordMin: "La contraseña debe tener al menos 8 caracteres",
        passwordUpper: "Debe contener una letra mayúscula",
        passwordNumber: "Debe contener un número",
        confirmRequired: "Por favor confirma tu contraseña",
        termsRequired: "Debes aceptar los términos",
        passwordsMismatch: "Las contraseñas no coinciden",
      },
    },
    forgotPassword: {
      pageTitle: "Restablecer contraseña | ENS",
      title: "Restablecer contraseña",
      description: "Introduce tu correo y te enviaremos un enlace de restablecimiento",
      emailLabel: "Correo electrónico",
      submit: "Enviar enlace",
      submitting: "Enviando enlace...",
      sentTitle: "Revisa tu bandeja de entrada",
      sentTo: "Enviamos un enlace de restablecimiento a",
      checkSpam: "Revisa la carpeta de spam si no lo ves en unos minutos.",
      resending: "Enviando...",
      resendIn: "Reenviar en {{seconds}}s",
      resendEmail: "Reenviar correo",
      differentEmail: "Usar otro correo",
      backToLogin: "Volver a inicio de sesión",
      validation: {
        email: "Por favor introduce una dirección de correo válida",
      },
    },
    resetPassword: {
      pageTitle: "Nueva contraseña | ENS",
      title: "Establecer nueva contraseña",
      description: "Elige una contraseña segura para tu cuenta",
      newPasswordLabel: "Nueva contraseña",
      confirmPasswordLabel: "Confirmar contraseña",
      passwordPlaceholder: "••••••••",
      submit: "Actualizar contraseña",
      submitting: "Actualizando contraseña...",
      successTitle: "Contraseña actualizada",
      successMessage: "Tu contraseña ha sido actualizada correctamente. Ahora puedes iniciar sesión con tus nuevas credenciales.",
      continueToSignIn: "Continuar al inicio de sesión",
      backToLogin: "Volver a inicio de sesión",
      showPassword: "Mostrar contraseña",
      hidePassword: "Ocultar contraseña",
      showConfirmPassword: "Mostrar confirmación",
      hideConfirmPassword: "Ocultar confirmación",
      requirements: {
        length: "Al menos 8 caracteres",
        uppercase: "Una letra mayúscula",
        number: "Un número",
      },
      strength: {
        weak: "Débil",
        fair: "Regular",
        good: "Buena",
        strong: "Fuerte",
        suffix: "contraseña",
      },
      validation: {
        passwordMin: "La contraseña debe tener al menos 8 caracteres",
        passwordUpper: "Debe contener al menos una letra mayúscula",
        passwordNumber: "Debe contener al menos un número",
        confirmRequired: "Por favor confirma tu contraseña",
        passwordsMismatch: "Las contraseñas no coinciden",
      },
    },
  },
  it: {
    login: {
      pageTitle: "Accedi | ENS",
      title: "Bentornato",
      description: "Accedi per entrare nella tua area di lavoro",
      emailLabel: "E-mail",
      emailPlaceholder: "nome@azienda.com",
      passwordLabel: "Password",
      passwordPlaceholder: "Inserisci la tua password",
      forgotPassword: "Password dimenticata?",
      rememberMe: "Mantieni l'accesso per 30 giorni",
      submit: "Accedi",
      submitting: "Accesso in corso...",
      lockedBtn: "Bloccato",
      lockMessage: "Account temporaneamente bloccato. Riprova tra {{time}}.",
      signInError: "Impossibile accedere.",
      attemptsRemaining_one: "{{count}} tentativo di accesso rimasto prima del blocco temporaneo",
      attemptsRemaining_other: "{{count}} tentativi di accesso rimasti prima del blocco temporaneo",
      noAccount: "Non hai un account?",
      signUpFree: "Registrati gratuitamente",
      devSection: "Account di test locali",
      showPassword: "Mostra password",
      hidePassword: "Nascondi password",
      validation: {
        email: "Indirizzo e-mail non valido",
        passwordMin: "La password deve contenere almeno 8 caratteri",
      },
    },
    signup: {
      pageTitle: "Crea account | ENS",
      title: "Crea account cliente",
      description: "La registrazione pubblica crea un account di revisione in attesa di approvazione",
      fullNameLabel: "Nome completo",
      fullNamePlaceholder: "Mario Rossi",
      companyLabel: "Azienda",
      companyPlaceholder: "Acme Esposizioni",
      workEmailLabel: "E-mail aziendale",
      passwordLabel: "Password",
      passwordPlaceholder: "Crea una password",
      confirmPasswordLabel: "Conferma password",
      confirmPasswordPlaceholder: "Conferma la tua password",
      termsLabel: "Accetto i",
      termsOfService: "Termini di servizio",
      and: "e la",
      privacyPolicy: "Informativa sulla privacy",
      submit: "Crea account cliente",
      submitting: "Creazione account...",
      createError: "Impossibile creare l'account.",
      haveAccount: "Hai già un account?",
      signIn: "Accedi",
      clientOnlyNote: "La registrazione pubblica è riservata ai clienti. I project manager e i responsabili devono essere invitati da un proprietario dell'organizzazione.",
      showPassword: "Mostra password",
      hidePassword: "Nascondi password",
      showConfirmPassword: "Mostra conferma password",
      hideConfirmPassword: "Nascondi conferma password",
      strength: {
        weak: "Debole",
        fair: "Sufficiente",
        good: "Buona",
        strong: "Forte",
        suffix: "password",
      },
      validation: {
        nameMin: "Il nome deve contenere almeno 2 caratteri",
        companyMin: "L'azienda deve contenere almeno 2 caratteri",
        email: "Indirizzo e-mail non valido",
        passwordMin: "La password deve contenere almeno 8 caratteri",
        passwordUpper: "Deve contenere una lettera maiuscola",
        passwordNumber: "Deve contenere un numero",
        confirmRequired: "Conferma la tua password",
        termsRequired: "Devi accettare i termini",
        passwordsMismatch: "Le password non corrispondono",
      },
    },
    forgotPassword: {
      pageTitle: "Reimposta password | ENS",
      title: "Reimposta password",
      description: "Inserisci la tua e-mail e ti invieremo un link di reimpostazione",
      emailLabel: "Indirizzo e-mail",
      submit: "Invia link",
      submitting: "Invio in corso...",
      sentTitle: "Controlla la tua casella di posta",
      sentTo: "Abbiamo inviato un link di reimpostazione a",
      checkSpam: "Controlla la cartella spam se non lo vedi entro qualche minuto.",
      resending: "Invio in corso...",
      resendIn: "Reinvia tra {{seconds}}s",
      resendEmail: "Reinvia e-mail",
      differentEmail: "Usa un'altra e-mail",
      backToLogin: "Torna al login",
      validation: {
        email: "Inserisci un indirizzo e-mail valido",
      },
    },
    resetPassword: {
      pageTitle: "Nuova password | ENS",
      title: "Imposta nuova password",
      description: "Scegli una password sicura per il tuo account",
      newPasswordLabel: "Nuova password",
      confirmPasswordLabel: "Conferma password",
      passwordPlaceholder: "••••••••",
      submit: "Aggiorna password",
      submitting: "Aggiornamento password...",
      successTitle: "Password aggiornata",
      successMessage: "La tua password è stata aggiornata con successo. Ora puoi accedere con le nuove credenziali.",
      continueToSignIn: "Continua all'accesso",
      backToLogin: "Torna al login",
      showPassword: "Mostra password",
      hidePassword: "Nascondi password",
      showConfirmPassword: "Mostra conferma",
      hideConfirmPassword: "Nascondi conferma",
      requirements: {
        length: "Almeno 8 caratteri",
        uppercase: "Una lettera maiuscola",
        number: "Un numero",
      },
      strength: {
        weak: "Debole",
        fair: "Sufficiente",
        good: "Buona",
        strong: "Forte",
        suffix: "password",
      },
      validation: {
        passwordMin: "La password deve contenere almeno 8 caratteri",
        passwordUpper: "Deve contenere almeno una lettera maiuscola",
        passwordNumber: "Deve contenere almeno un numero",
        confirmRequired: "Conferma la tua password",
        passwordsMismatch: "Le password non corrispondono",
      },
    },
  },
  pt: {
    login: {
      pageTitle: "Entrar | ENS",
      title: "Bem-vindo de volta",
      description: "Entre para acessar seu espaço de trabalho",
      emailLabel: "E-mail",
      emailPlaceholder: "nome@empresa.com",
      passwordLabel: "Senha",
      passwordPlaceholder: "Digite sua senha",
      forgotPassword: "Esqueceu a senha?",
      rememberMe: "Manter conectado por 30 dias",
      submit: "Entrar",
      submitting: "Entrando...",
      lockedBtn: "Bloqueado",
      lockMessage: "Conta temporariamente bloqueada. Tente novamente em {{time}}.",
      signInError: "Não foi possível entrar.",
      attemptsRemaining_one: "{{count}} tentativa de login restante antes do bloqueio temporário",
      attemptsRemaining_other: "{{count}} tentativas de login restantes antes do bloqueio temporário",
      noAccount: "Não tem uma conta?",
      signUpFree: "Cadastre-se grátis",
      devSection: "Contas de teste locais",
      showPassword: "Mostrar senha",
      hidePassword: "Ocultar senha",
      validation: {
        email: "Endereço de e-mail inválido",
        passwordMin: "A senha deve ter pelo menos 8 caracteres",
      },
    },
    signup: {
      pageTitle: "Criar conta | ENS",
      title: "Criar conta de cliente",
      description: "O cadastro público cria uma conta de revisão aguardando aprovação",
      fullNameLabel: "Nome completo",
      fullNamePlaceholder: "João Silva",
      companyLabel: "Empresa",
      companyPlaceholder: "Acme Exposições",
      workEmailLabel: "E-mail profissional",
      passwordLabel: "Senha",
      passwordPlaceholder: "Criar uma senha",
      confirmPasswordLabel: "Confirmar senha",
      confirmPasswordPlaceholder: "Confirme sua senha",
      termsLabel: "Concordo com os",
      termsOfService: "Termos de serviço",
      and: "e a",
      privacyPolicy: "Política de privacidade",
      submit: "Criar conta de cliente",
      submitting: "Criando conta...",
      createError: "Não foi possível criar a conta.",
      haveAccount: "Já tem uma conta?",
      signIn: "Entrar",
      clientOnlyNote: "O cadastro público é limitado a clientes. Gerentes de projeto e responsáveis devem ser convidados por um proprietário da organização.",
      showPassword: "Mostrar senha",
      hidePassword: "Ocultar senha",
      showConfirmPassword: "Mostrar confirmação de senha",
      hideConfirmPassword: "Ocultar confirmação de senha",
      strength: {
        weak: "Fraca",
        fair: "Regular",
        good: "Boa",
        strong: "Forte",
        suffix: "senha",
      },
      validation: {
        nameMin: "O nome deve ter pelo menos 2 caracteres",
        companyMin: "A empresa deve ter pelo menos 2 caracteres",
        email: "Endereço de e-mail inválido",
        passwordMin: "A senha deve ter pelo menos 8 caracteres",
        passwordUpper: "Deve conter uma letra maiúscula",
        passwordNumber: "Deve conter um número",
        confirmRequired: "Por favor confirme sua senha",
        termsRequired: "Você deve aceitar os termos",
        passwordsMismatch: "As senhas não coincidem",
      },
    },
    forgotPassword: {
      pageTitle: "Redefinir senha | ENS",
      title: "Redefinir senha",
      description: "Insira seu e-mail e enviaremos um link de redefinição",
      emailLabel: "Endereço de e-mail",
      submit: "Enviar link",
      submitting: "Enviando link...",
      sentTitle: "Verifique sua caixa de entrada",
      sentTo: "Enviamos um link de redefinição de senha para",
      checkSpam: "Verifique a pasta de spam se não encontrar em alguns minutos.",
      resending: "Enviando...",
      resendIn: "Reenviar em {{seconds}}s",
      resendEmail: "Reenviar e-mail",
      differentEmail: "Usar outro e-mail",
      backToLogin: "Voltar ao login",
      validation: {
        email: "Por favor insira um endereço de e-mail válido",
      },
    },
    resetPassword: {
      pageTitle: "Nova senha | ENS",
      title: "Definir nova senha",
      description: "Escolha uma senha forte para sua conta",
      newPasswordLabel: "Nova senha",
      confirmPasswordLabel: "Confirmar senha",
      passwordPlaceholder: "••••••••",
      submit: "Atualizar senha",
      submitting: "Atualizando senha...",
      successTitle: "Senha atualizada",
      successMessage: "Sua senha foi atualizada com sucesso. Agora você pode entrar com suas novas credenciais.",
      continueToSignIn: "Continuar para entrar",
      backToLogin: "Voltar ao login",
      showPassword: "Mostrar senha",
      hidePassword: "Ocultar senha",
      showConfirmPassword: "Mostrar confirmação",
      hideConfirmPassword: "Ocultar confirmação",
      requirements: {
        length: "Pelo menos 8 caracteres",
        uppercase: "Uma letra maiúscula",
        number: "Um número",
      },
      strength: {
        weak: "Fraca",
        fair: "Regular",
        good: "Boa",
        strong: "Forte",
        suffix: "senha",
      },
      validation: {
        passwordMin: "A senha deve ter pelo menos 8 caracteres",
        passwordUpper: "Deve conter pelo menos uma letra maiúscula",
        passwordNumber: "Deve conter pelo menos um número",
        confirmRequired: "Por favor confirme sua senha",
        passwordsMismatch: "As senhas não coincidem",
      },
    },
  },
  nl: {
    login: {
      pageTitle: "Inloggen | ENS",
      title: "Welkom terug",
      description: "Log in om toegang te krijgen tot uw werkruimte",
      emailLabel: "E-mail",
      emailPlaceholder: "naam@bedrijf.com",
      passwordLabel: "Wachtwoord",
      passwordPlaceholder: "Voer uw wachtwoord in",
      forgotPassword: "Wachtwoord vergeten?",
      rememberMe: "30 dagen ingelogd blijven",
      submit: "Inloggen",
      submitting: "Inloggen...",
      lockedBtn: "Vergrendeld",
      lockMessage: "Account tijdelijk vergrendeld. Probeer opnieuw over {{time}}.",
      signInError: "Inloggen mislukt.",
      attemptsRemaining_one: "{{count}} inlogpoging over voor tijdelijke blokkade",
      attemptsRemaining_other: "{{count}} inlogpogingen over voor tijdelijke blokkade",
      noAccount: "Nog geen account?",
      signUpFree: "Gratis registreren",
      devSection: "Lokale testaccounts",
      showPassword: "Wachtwoord tonen",
      hidePassword: "Wachtwoord verbergen",
      validation: {
        email: "Ongeldig e-mailadres",
        passwordMin: "Wachtwoord moet minimaal 8 tekens bevatten",
      },
    },
    signup: {
      pageTitle: "Account aanmaken | ENS",
      title: "Klantaccount aanmaken",
      description: "Publieke registratie maakt een beoordelingsaccount aan dat goedkeuring vereist",
      fullNameLabel: "Volledige naam",
      fullNamePlaceholder: "Jan de Vries",
      companyLabel: "Bedrijf",
      companyPlaceholder: "Acme Beurzen",
      workEmailLabel: "Zakelijk e-mailadres",
      passwordLabel: "Wachtwoord",
      passwordPlaceholder: "Wachtwoord aanmaken",
      confirmPasswordLabel: "Wachtwoord bevestigen",
      confirmPasswordPlaceholder: "Wachtwoord bevestigen",
      termsLabel: "Ik ga akkoord met de",
      termsOfService: "Servicevoorwaarden",
      and: "en het",
      privacyPolicy: "Privacybeleid",
      submit: "Klantaccount aanmaken",
      submitting: "Account aanmaken...",
      createError: "Account aanmaken mislukt.",
      haveAccount: "Al een account?",
      signIn: "Inloggen",
      clientOnlyNote: "Publieke registratie is beperkt tot klanten. Projectmanagers en leidinggevenden moeten worden uitgenodigd door een organisatie-eigenaar.",
      showPassword: "Wachtwoord tonen",
      hidePassword: "Wachtwoord verbergen",
      showConfirmPassword: "Bevestigingswachtwoord tonen",
      hideConfirmPassword: "Bevestigingswachtwoord verbergen",
      strength: {
        weak: "Zwak",
        fair: "Matig",
        good: "Goed",
        strong: "Sterk",
        suffix: "wachtwoord",
      },
      validation: {
        nameMin: "Naam moet minimaal 2 tekens bevatten",
        companyMin: "Bedrijf moet minimaal 2 tekens bevatten",
        email: "Ongeldig e-mailadres",
        passwordMin: "Wachtwoord moet minimaal 8 tekens bevatten",
        passwordUpper: "Moet een hoofdletter bevatten",
        passwordNumber: "Moet een cijfer bevatten",
        confirmRequired: "Bevestig uw wachtwoord",
        termsRequired: "U moet de voorwaarden accepteren",
        passwordsMismatch: "Wachtwoorden komen niet overeen",
      },
    },
    forgotPassword: {
      pageTitle: "Wachtwoord opnieuw instellen | ENS",
      title: "Wachtwoord opnieuw instellen",
      description: "Voer uw e-mail in en we sturen u een resetlink",
      emailLabel: "E-mailadres",
      submit: "Link versturen",
      submitting: "Link versturen...",
      sentTitle: "Controleer uw inbox",
      sentTo: "We hebben een wachtwoord-resetlink verstuurd naar",
      checkSpam: "Controleer uw spam-map als u de e-mail niet binnen enkele minuten ziet.",
      resending: "Versturen...",
      resendIn: "Opnieuw versturen over {{seconds}}s",
      resendEmail: "E-mail opnieuw versturen",
      differentEmail: "Ander e-mailadres gebruiken",
      backToLogin: "Terug naar inloggen",
      validation: {
        email: "Voer een geldig e-mailadres in",
      },
    },
    resetPassword: {
      pageTitle: "Nieuw wachtwoord | ENS",
      title: "Nieuw wachtwoord instellen",
      description: "Kies een sterk wachtwoord voor uw account",
      newPasswordLabel: "Nieuw wachtwoord",
      confirmPasswordLabel: "Wachtwoord bevestigen",
      passwordPlaceholder: "••••••••",
      submit: "Wachtwoord bijwerken",
      submitting: "Wachtwoord bijwerken...",
      successTitle: "Wachtwoord bijgewerkt",
      successMessage: "Uw wachtwoord is succesvol bijgewerkt. U kunt nu inloggen met uw nieuwe gegevens.",
      continueToSignIn: "Doorgaan naar inloggen",
      backToLogin: "Terug naar inloggen",
      showPassword: "Wachtwoord tonen",
      hidePassword: "Wachtwoord verbergen",
      showConfirmPassword: "Bevestiging tonen",
      hideConfirmPassword: "Bevestiging verbergen",
      requirements: {
        length: "Minimaal 8 tekens",
        uppercase: "Een hoofdletter",
        number: "Een cijfer",
      },
      strength: {
        weak: "Zwak",
        fair: "Matig",
        good: "Goed",
        strong: "Sterk",
        suffix: "wachtwoord",
      },
      validation: {
        passwordMin: "Wachtwoord moet minimaal 8 tekens bevatten",
        passwordUpper: "Moet minimaal één hoofdletter bevatten",
        passwordNumber: "Moet minimaal één cijfer bevatten",
        confirmRequired: "Bevestig uw wachtwoord",
        passwordsMismatch: "Wachtwoorden komen niet overeen",
      },
    },
  },
  zh: {
    login: {
      pageTitle: "登录 | ENS",
      title: "欢迎回来",
      description: "登录以访问您的工作区",
      emailLabel: "电子邮件",
      emailPlaceholder: "姓名@公司.com",
      passwordLabel: "密码",
      passwordPlaceholder: "输入您的密码",
      forgotPassword: "忘记密码？",
      rememberMe: "保持登录 30 天",
      submit: "登录",
      submitting: "正在登录...",
      lockedBtn: "已锁定",
      lockMessage: "账户已被临时锁定。请在 {{time}} 后重试。",
      signInError: "无法登录。",
      attemptsRemaining_one: "临时锁定前还剩 {{count}} 次登录尝试",
      attemptsRemaining_other: "临时锁定前还剩 {{count}} 次登录尝试",
      noAccount: "还没有账户？",
      signUpFree: "免费注册",
      devSection: "本地测试账户",
      showPassword: "显示密码",
      hidePassword: "隐藏密码",
      validation: {
        email: "无效的电子邮件地址",
        passwordMin: "密码至少需要 8 个字符",
      },
    },
    signup: {
      pageTitle: "创建账户 | ENS",
      title: "创建客户账户",
      description: "公开注册将创建一个待代理商审批的审核账户",
      fullNameLabel: "全名",
      fullNamePlaceholder: "张三",
      companyLabel: "公司",
      companyPlaceholder: "Acme 展览",
      workEmailLabel: "工作邮箱",
      passwordLabel: "密码",
      passwordPlaceholder: "创建密码",
      confirmPasswordLabel: "确认密码",
      confirmPasswordPlaceholder: "确认您的密码",
      termsLabel: "我同意",
      termsOfService: "服务条款",
      and: "和",
      privacyPolicy: "隐私政策",
      submit: "创建客户账户",
      submitting: "正在创建账户...",
      createError: "无法创建账户。",
      haveAccount: "已有账户？",
      signIn: "登录",
      clientOnlyNote: "公开注册仅限客户。项目经理和负责人必须由组织所有者邀请。",
      showPassword: "显示密码",
      hidePassword: "隐藏密码",
      showConfirmPassword: "显示确认密码",
      hideConfirmPassword: "隐藏确认密码",
      strength: {
        weak: "弱",
        fair: "一般",
        good: "良好",
        strong: "强",
        suffix: "密码",
      },
      validation: {
        nameMin: "姓名至少需要 2 个字符",
        companyMin: "公司名称至少需要 2 个字符",
        email: "无效的电子邮件地址",
        passwordMin: "密码至少需要 8 个字符",
        passwordUpper: "必须包含一个大写字母",
        passwordNumber: "必须包含一个数字",
        confirmRequired: "请确认您的密码",
        termsRequired: "您必须接受条款",
        passwordsMismatch: "密码不匹配",
      },
    },
    forgotPassword: {
      pageTitle: "重置密码 | ENS",
      title: "重置密码",
      description: "输入您的电子邮件，我们将发送重置链接",
      emailLabel: "电子邮件地址",
      submit: "发送重置链接",
      submitting: "发送链接中...",
      sentTitle: "查看您的收件箱",
      sentTo: "我们已将密码重置链接发送至",
      checkSpam: "如果几分钟内没有看到，请检查垃圾邮件文件夹。",
      resending: "发送中...",
      resendIn: "{{seconds}}s 后重新发送",
      resendEmail: "重新发送邮件",
      differentEmail: "使用其他邮箱",
      backToLogin: "返回登录",
      validation: {
        email: "请输入有效的电子邮件地址",
      },
    },
    resetPassword: {
      pageTitle: "设置新密码 | ENS",
      title: "设置新密码",
      description: "为您的账户选择一个强密码",
      newPasswordLabel: "新密码",
      confirmPasswordLabel: "确认密码",
      passwordPlaceholder: "••••••••",
      submit: "更新密码",
      submitting: "正在更新密码...",
      successTitle: "密码已更新",
      successMessage: "您的密码已成功更新。现在可以使用新凭据登录。",
      continueToSignIn: "继续登录",
      backToLogin: "返回登录",
      showPassword: "显示密码",
      hidePassword: "隐藏密码",
      showConfirmPassword: "显示确认",
      hideConfirmPassword: "隐藏确认",
      requirements: {
        length: "至少 8 个字符",
        uppercase: "一个大写字母",
        number: "一个数字",
      },
      strength: {
        weak: "弱",
        fair: "一般",
        good: "良好",
        strong: "强",
        suffix: "密码",
      },
      validation: {
        passwordMin: "密码至少需要 8 个字符",
        passwordUpper: "必须包含至少一个大写字母",
        passwordNumber: "必须包含至少一个数字",
        confirmRequired: "请确认您的密码",
        passwordsMismatch: "密码不匹配",
      },
    },
  },
  ja: {
    login: {
      pageTitle: "ログイン | ENS",
      title: "おかえりなさい",
      description: "ワークスペースにアクセスするためにログインしてください",
      emailLabel: "メールアドレス",
      emailPlaceholder: "名前@会社.com",
      passwordLabel: "パスワード",
      passwordPlaceholder: "パスワードを入力",
      forgotPassword: "パスワードをお忘れですか？",
      rememberMe: "30日間ログイン状態を保持",
      submit: "ログイン",
      submitting: "ログイン中...",
      lockedBtn: "ロック済み",
      lockMessage: "アカウントが一時的にロックされています。{{time}}後にもう一度お試しください。",
      signInError: "ログインできませんでした。",
      attemptsRemaining_one: "一時的なロックまであと {{count}} 回のログイン試行が残っています",
      attemptsRemaining_other: "一時的なロックまであと {{count}} 回のログイン試行が残っています",
      noAccount: "アカウントをお持ちでない方は？",
      signUpFree: "無料登録",
      devSection: "ローカルテストアカウント",
      showPassword: "パスワードを表示",
      hidePassword: "パスワードを非表示",
      validation: {
        email: "無効なメールアドレスです",
        passwordMin: "パスワードは8文字以上必要です",
      },
    },
    signup: {
      pageTitle: "アカウント作成 | ENS",
      title: "クライアントアカウントを作成",
      description: "公開登録では、代理店承認待ちのレビューアカウントが作成されます",
      fullNameLabel: "氏名",
      fullNamePlaceholder: "山田 太郎",
      companyLabel: "会社名",
      companyPlaceholder: "株式会社 展示",
      workEmailLabel: "業務用メールアドレス",
      passwordLabel: "パスワード",
      passwordPlaceholder: "パスワードを作成",
      confirmPasswordLabel: "パスワードを確認",
      confirmPasswordPlaceholder: "パスワードを確認",
      termsLabel: "に同意します",
      termsOfService: "利用規約",
      and: "および",
      privacyPolicy: "プライバシーポリシー",
      submit: "クライアントアカウントを作成",
      submitting: "アカウント作成中...",
      createError: "アカウントを作成できませんでした。",
      haveAccount: "すでにアカウントをお持ちですか？",
      signIn: "ログイン",
      clientOnlyNote: "公開登録はクライアントのみに制限されています。プロジェクトマネージャーと責任者は組織オーナーから招待される必要があります。",
      showPassword: "パスワードを表示",
      hidePassword: "パスワードを非表示",
      showConfirmPassword: "確認パスワードを表示",
      hideConfirmPassword: "確認パスワードを非表示",
      strength: {
        weak: "弱い",
        fair: "普通",
        good: "良い",
        strong: "強い",
        suffix: "パスワード",
      },
      validation: {
        nameMin: "名前は2文字以上必要です",
        companyMin: "会社名は2文字以上必要です",
        email: "無効なメールアドレスです",
        passwordMin: "パスワードは8文字以上必要です",
        passwordUpper: "大文字を含める必要があります",
        passwordNumber: "数字を含める必要があります",
        confirmRequired: "パスワードを確認してください",
        termsRequired: "利用規約に同意する必要があります",
        passwordsMismatch: "パスワードが一致しません",
      },
    },
    forgotPassword: {
      pageTitle: "パスワードのリセット | ENS",
      title: "パスワードをリセット",
      description: "メールアドレスを入力するとリセットリンクをお送りします",
      emailLabel: "メールアドレス",
      submit: "リセットリンクを送信",
      submitting: "送信中...",
      sentTitle: "受信トレイを確認してください",
      sentTo: "パスワードリセットリンクを送信しました：",
      checkSpam: "数分以内に届かない場合は、迷惑メールフォルダを確認してください。",
      resending: "送信中...",
      resendIn: "{{seconds}}秒後に再送信",
      resendEmail: "メールを再送信",
      differentEmail: "別のメールアドレスを使用",
      backToLogin: "ログインに戻る",
      validation: {
        email: "有効なメールアドレスを入力してください",
      },
    },
    resetPassword: {
      pageTitle: "新しいパスワードを設定 | ENS",
      title: "新しいパスワードを設定",
      description: "アカウントの強力なパスワードを選択してください",
      newPasswordLabel: "新しいパスワード",
      confirmPasswordLabel: "パスワードを確認",
      passwordPlaceholder: "••••••••",
      submit: "パスワードを更新",
      submitting: "パスワード更新中...",
      successTitle: "パスワードが更新されました",
      successMessage: "パスワードが正常に更新されました。新しい認証情報でログインできます。",
      continueToSignIn: "ログインへ進む",
      backToLogin: "ログインに戻る",
      showPassword: "パスワードを表示",
      hidePassword: "パスワードを非表示",
      showConfirmPassword: "確認を表示",
      hideConfirmPassword: "確認を非表示",
      requirements: {
        length: "8文字以上",
        uppercase: "大文字1文字以上",
        number: "数字1文字以上",
      },
      strength: {
        weak: "弱い",
        fair: "普通",
        good: "良い",
        strong: "強い",
        suffix: "パスワード",
      },
      validation: {
        passwordMin: "パスワードは8文字以上必要です",
        passwordUpper: "大文字を1文字以上含める必要があります",
        passwordNumber: "数字を1文字以上含める必要があります",
        confirmRequired: "パスワードを確認してください",
        passwordsMismatch: "パスワードが一致しません",
      },
    },
  },
  ar: {
    login: {
      pageTitle: "تسجيل الدخول | ENS",
      title: "مرحباً بعودتك",
      description: "سجّل الدخول للوصول إلى مساحة عملك",
      emailLabel: "البريد الإلكتروني",
      emailPlaceholder: "الاسم@الشركة.com",
      passwordLabel: "كلمة المرور",
      passwordPlaceholder: "أدخل كلمة المرور",
      forgotPassword: "هل نسيت كلمة المرور؟",
      rememberMe: "البقاء متصلاً لمدة 30 يوماً",
      submit: "تسجيل الدخول",
      submitting: "جارٍ تسجيل الدخول...",
      lockedBtn: "مقفل",
      lockMessage: "تم قفل الحساب مؤقتاً. حاول مرة أخرى بعد {{time}}.",
      signInError: "تعذّر تسجيل الدخول.",
      attemptsRemaining_one: "متبقٍ {{count}} محاولة تسجيل دخول قبل القفل المؤقت",
      attemptsRemaining_other: "متبقٍ {{count}} محاولات تسجيل دخول قبل القفل المؤقت",
      noAccount: "ليس لديك حساب؟",
      signUpFree: "التسجيل مجاناً",
      devSection: "حسابات الاختبار المحلية",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور",
      validation: {
        email: "عنوان البريد الإلكتروني غير صالح",
        passwordMin: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
      },
    },
    signup: {
      pageTitle: "إنشاء حساب | ENS",
      title: "إنشاء حساب عميل",
      description: "التسجيل العام يُنشئ حساب مراجعة في انتظار موافقة الوكالة",
      fullNameLabel: "الاسم الكامل",
      fullNamePlaceholder: "محمد عبدالله",
      companyLabel: "الشركة",
      companyPlaceholder: "شركة المعارض",
      workEmailLabel: "البريد الإلكتروني للعمل",
      passwordLabel: "كلمة المرور",
      passwordPlaceholder: "إنشاء كلمة مرور",
      confirmPasswordLabel: "تأكيد كلمة المرور",
      confirmPasswordPlaceholder: "تأكيد كلمة المرور",
      termsLabel: "أوافق على",
      termsOfService: "شروط الخدمة",
      and: "و",
      privacyPolicy: "سياسة الخصوصية",
      submit: "إنشاء حساب عميل",
      submitting: "جارٍ إنشاء الحساب...",
      createError: "تعذّر إنشاء الحساب.",
      haveAccount: "لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
      clientOnlyNote: "التسجيل العام مقتصر على العملاء. يجب على مديري المشاريع والمسؤولين أن يُدعَوا من قِبل مالك المؤسسة.",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور",
      showConfirmPassword: "إظهار تأكيد كلمة المرور",
      hideConfirmPassword: "إخفاء تأكيد كلمة المرور",
      strength: {
        weak: "ضعيفة",
        fair: "مقبولة",
        good: "جيدة",
        strong: "قوية",
        suffix: "كلمة المرور",
      },
      validation: {
        nameMin: "يجب أن يكون الاسم حرفين على الأقل",
        companyMin: "يجب أن يكون اسم الشركة حرفين على الأقل",
        email: "عنوان البريد الإلكتروني غير صالح",
        passwordMin: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        passwordUpper: "يجب أن تحتوي على حرف كبير",
        passwordNumber: "يجب أن تحتوي على رقم",
        confirmRequired: "يرجى تأكيد كلمة المرور",
        termsRequired: "يجب قبول الشروط",
        passwordsMismatch: "كلمتا المرور غير متطابقتين",
      },
    },
    forgotPassword: {
      pageTitle: "إعادة تعيين كلمة المرور | ENS",
      title: "إعادة تعيين كلمة المرور",
      description: "أدخل بريدك الإلكتروني وسنرسل لك رابط إعادة التعيين",
      emailLabel: "عنوان البريد الإلكتروني",
      submit: "إرسال الرابط",
      submitting: "جارٍ إرسال الرابط...",
      sentTitle: "تحقق من صندوق الوارد",
      sentTo: "أرسلنا رابط إعادة تعيين كلمة المرور إلى",
      checkSpam: "تحقق من مجلد البريد غير المرغوب فيه إن لم تجده خلال بضع دقائق.",
      resending: "جارٍ الإرسال...",
      resendIn: "إعادة الإرسال بعد {{seconds}}ث",
      resendEmail: "إعادة إرسال البريد الإلكتروني",
      differentEmail: "استخدام بريد إلكتروني مختلف",
      backToLogin: "العودة إلى تسجيل الدخول",
      validation: {
        email: "يرجى إدخال عنوان بريد إلكتروني صالح",
      },
    },
    resetPassword: {
      pageTitle: "تعيين كلمة مرور جديدة | ENS",
      title: "تعيين كلمة مرور جديدة",
      description: "اختر كلمة مرور قوية لحسابك",
      newPasswordLabel: "كلمة المرور الجديدة",
      confirmPasswordLabel: "تأكيد كلمة المرور",
      passwordPlaceholder: "••••••••",
      submit: "تحديث كلمة المرور",
      submitting: "جارٍ تحديث كلمة المرور...",
      successTitle: "تم تحديث كلمة المرور",
      successMessage: "تم تحديث كلمة مرورك بنجاح. يمكنك الآن تسجيل الدخول بالبيانات الجديدة.",
      continueToSignIn: "المتابعة لتسجيل الدخول",
      backToLogin: "العودة إلى تسجيل الدخول",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور",
      showConfirmPassword: "إظهار التأكيد",
      hideConfirmPassword: "إخفاء التأكيد",
      requirements: {
        length: "8 أحرف على الأقل",
        uppercase: "حرف كبير واحد",
        number: "رقم واحد",
      },
      strength: {
        weak: "ضعيفة",
        fair: "مقبولة",
        good: "جيدة",
        strong: "قوية",
        suffix: "كلمة المرور",
      },
      validation: {
        passwordMin: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
        passwordUpper: "يجب أن تحتوي على حرف كبير واحد على الأقل",
        passwordNumber: "يجب أن تحتوي على رقم واحد على الأقل",
        confirmRequired: "يرجى تأكيد كلمة المرور",
        passwordsMismatch: "كلمتا المرور غير متطابقتين",
      },
    },
  },
  tr: {
    login: {
      pageTitle: "Giriş Yap | ENS",
      title: "Tekrar hoş geldiniz",
      description: "Çalışma alanınıza erişmek için giriş yapın",
      emailLabel: "E-posta",
      emailPlaceholder: "ad@sirket.com",
      passwordLabel: "Şifre",
      passwordPlaceholder: "Şifrenizi girin",
      forgotPassword: "Şifrenizi mi unuttunuz?",
      rememberMe: "30 gün boyunca giriş bilgilerimi hatırla",
      submit: "Giriş Yap",
      submitting: "Giriş yapılıyor...",
      lockedBtn: "Kilitli",
      lockMessage: "Hesap geçici olarak kilitlendi. {{time}} sonra tekrar deneyin.",
      signInError: "Giriş yapılamadı.",
      attemptsRemaining_one: "Geçici kilit öncesi {{count}} giriş denemesi kaldı",
      attemptsRemaining_other: "Geçici kilit öncesi {{count}} giriş denemesi kaldı",
      noAccount: "Hesabınız yok mu?",
      signUpFree: "Ücretsiz kayıt ol",
      devSection: "Yerel Test Hesapları",
      showPassword: "Şifreyi göster",
      hidePassword: "Şifreyi gizle",
      validation: {
        email: "Geçersiz e-posta adresi",
        passwordMin: "Şifre en az 8 karakter olmalıdır",
      },
    },
    signup: {
      pageTitle: "Hesap Oluştur | ENS",
      title: "Müşteri hesabı oluştur",
      description: "Genel kayıt, ajans onayı bekleyen bir inceleme hesabı oluşturur",
      fullNameLabel: "Tam Ad",
      fullNamePlaceholder: "Ahmet Yılmaz",
      companyLabel: "Şirket",
      companyPlaceholder: "Acme Fuar",
      workEmailLabel: "İş E-postası",
      passwordLabel: "Şifre",
      passwordPlaceholder: "Şifre oluştur",
      confirmPasswordLabel: "Şifreyi Onayla",
      confirmPasswordPlaceholder: "Şifrenizi onaylayın",
      termsLabel: "Kabul ediyorum",
      termsOfService: "Kullanım Koşulları",
      and: "ve",
      privacyPolicy: "Gizlilik Politikası",
      submit: "Müşteri Hesabı Oluştur",
      submitting: "Hesap oluşturuluyor...",
      createError: "Hesap oluşturulamadı.",
      haveAccount: "Zaten hesabınız var mı?",
      signIn: "Giriş yap",
      clientOnlyNote: "Genel kayıt yalnızca müşterilerle sınırlıdır. Proje yöneticileri ve sorumlular bir kuruluş sahibi tarafından davet edilmelidir.",
      showPassword: "Şifreyi göster",
      hidePassword: "Şifreyi gizle",
      showConfirmPassword: "Onay şifresini göster",
      hideConfirmPassword: "Onay şifresini gizle",
      strength: {
        weak: "Zayıf",
        fair: "Orta",
        good: "İyi",
        strong: "Güçlü",
        suffix: "şifre",
      },
      validation: {
        nameMin: "Ad en az 2 karakter olmalıdır",
        companyMin: "Şirket adı en az 2 karakter olmalıdır",
        email: "Geçersiz e-posta adresi",
        passwordMin: "Şifre en az 8 karakter olmalıdır",
        passwordUpper: "Büyük harf içermelidir",
        passwordNumber: "Rakam içermelidir",
        confirmRequired: "Lütfen şifrenizi onaylayın",
        termsRequired: "Koşulları kabul etmelisiniz",
        passwordsMismatch: "Şifreler eşleşmiyor",
      },
    },
    forgotPassword: {
      pageTitle: "Şifre Sıfırla | ENS",
      title: "Şifre sıfırla",
      description: "E-postanızı girin ve size bir sıfırlama bağlantısı gönderelim",
      emailLabel: "E-posta adresi",
      submit: "Bağlantı Gönder",
      submitting: "Bağlantı gönderiliyor...",
      sentTitle: "Gelen kutunuzu kontrol edin",
      sentTo: "Şifre sıfırlama bağlantısı gönderildi:",
      checkSpam: "Birkaç dakika içinde göremiyorsanız spam klasörünüzü kontrol edin.",
      resending: "Gönderiliyor...",
      resendIn: "{{seconds}}s sonra yeniden gönder",
      resendEmail: "E-postayı yeniden gönder",
      differentEmail: "Farklı e-posta kullan",
      backToLogin: "Girişe geri dön",
      validation: {
        email: "Lütfen geçerli bir e-posta adresi girin",
      },
    },
    resetPassword: {
      pageTitle: "Yeni Şifre Belirle | ENS",
      title: "Yeni şifre belirle",
      description: "Hesabınız için güçlü bir şifre seçin",
      newPasswordLabel: "Yeni Şifre",
      confirmPasswordLabel: "Şifreyi Onayla",
      passwordPlaceholder: "••••••••",
      submit: "Şifreyi Güncelle",
      submitting: "Şifre güncelleniyor...",
      successTitle: "Şifre güncellendi",
      successMessage: "Şifreniz başarıyla güncellendi. Artık yeni kimlik bilgilerinizle giriş yapabilirsiniz.",
      continueToSignIn: "Girişe devam et",
      backToLogin: "Girişe geri dön",
      showPassword: "Şifreyi göster",
      hidePassword: "Şifreyi gizle",
      showConfirmPassword: "Onayı göster",
      hideConfirmPassword: "Onayı gizle",
      requirements: {
        length: "En az 8 karakter",
        uppercase: "Bir büyük harf",
        number: "Bir rakam",
      },
      strength: {
        weak: "Zayıf",
        fair: "Orta",
        good: "İyi",
        strong: "Güçlü",
        suffix: "şifre",
      },
      validation: {
        passwordMin: "Şifre en az 8 karakter olmalıdır",
        passwordUpper: "En az bir büyük harf içermelidir",
        passwordNumber: "En az bir rakam içermelidir",
        confirmRequired: "Lütfen şifrenizi onaylayın",
        passwordsMismatch: "Şifreler eşleşmiyor",
      },
    },
  },
};

function deepMerge(target, source) {
  const result = Object.assign({}, target);
  for (const key of Object.keys(source)) {
    if (
      source[key] &&
      typeof source[key] === "object" &&
      !Array.isArray(source[key])
    ) {
      result[key] = deepMerge(target[key] ?? {}, source[key]);
    } else if (!(key in result)) {
      result[key] = source[key];
    }
  }
  return result;
}

let updated = 0;
let skipped = 0;

for (const [lang, keys] of Object.entries(TRANSLATIONS)) {
  const filePath = path.join(LOCALES_DIR, `${lang}.json`);
  if (!fs.existsSync(filePath)) {
    console.warn(`  SKIP  ${lang} — file not found`);
    skipped++;
    continue;
  }

  const raw = fs.readFileSync(filePath, "utf8");
  const json = JSON.parse(raw);

  if (!json.auth) json.auth = {};

  json.auth = deepMerge(json.auth, keys);

  fs.writeFileSync(filePath, JSON.stringify(json, null, 2) + "\n", "utf8");
  console.log(`  OK    ${lang}`);
  updated++;
}

console.log(`\nDone. Updated: ${updated}, Skipped: ${skipped}`);
